### ISSUE TITLE
Error: "file not written"

### ISSUE THREAD

**Issue by vzlgdu** [twrecked/pyaarlo#26]
Hi, why I receive message "file not written" when I change state?

Thanks

**Comment by twrecked** [comment]
`pyaarlo` will try and save its state every so often, it's a feature that helps home assistant startup faster - we load the old state on startup and fill in the new state in the background. By default it tries to save it in "/config/.aarlo" so you're seeing the error because it's probably unable to write the file.

You probably don't need it for quickie scripts so you can add the `save_state` parameter to your start up code.

```python
arlo = pyaarlo.PyArlo(username=USERNAME,password=PASSWORD,
                      save_state=False)
```

I'll make the default to `save_state` to `False`, it makes more sense for `pyaarlo`.

**Comment by vzlgdu** [comment]
Thanks!
